#!/bin/bash

statefile="$HOME/.nightlight_state"

while true;
do
  [ -f "$statefile" ] && { [ "$(date '+%H')" -gt "18" ] || [ "$(date '+%H')" -lt "6" ] && \
  redshift -O 1000 >/dev/null 2>&1; } || \
  redshift -x >/dev/null 2>&1
	sleep 1
done
